export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const SIGNUP_RESPONSE = "SIGNUP_RESPONSE";
export const RECEIVE_STATISTICS_DATA = "RECEIVE_STATISTICS_DATA";
export const RECEIVE_CORRELATIONS_DATA = "RECEIVE_CORRELATIONS_DATA";
